services:
  app:
    image: 'nothingbutlucas/nestseekerbot:latest'
    environment:
      TOKEN: "7431683842:AAFSMrFMEWeAgiOPTk3RFIeRiMqeptq8t4c"
      ROOM: "-4543384373"
      LOGGING_LEVEL: INFO
      HORAS: 2
    command: ["python3", "-u", "main.py"] 
    volumes: 
      - /root/nestseekerbot/seen.txt:/app/seen.txt
      - /root/nestseekerbot/frases.txt:/app/frases.txt
      - /root/nestseekerbot/sitios.txt:/app/sitios.